production:
  environment: production
  production_environment: true
  payload:
    url: https://mobile.sentrei.com

staging:
  auto_deploy_on: refs/heads/master
  environment: staging
  production_environment: false
  payload:
    url: https://mobile.sentrei.com

review:
  environment: PR${{ pr }}
  transient_environment: true
  production_environment: false
  payload:
    url: https://staging.mobile.sentrei.com
