design-production:
  auto_deploy_on: refs/heads/master
  environment: "Design Production"
  production_environment: true
  task: design
  payload:
    type: design
    url: https://design.sentrei.com
design-staging:
  environment: "Design Staging PR ${{ pr }}"
  transient_environment: true
  production_environment: false
  task: staging-design
  payload:
    type: design
    url: https://staging.design.sentrei.com
mobile-production-alpha:
  auto_deploy_on: refs/heads/alpha
  environment: "Mobile Production Alpha"
  production_environment: true
  task: alpha
  payload:
    type: mobile
    url: https://alpha.mobile.sentrei.com
mobile-staging-alpha:
  environment: "Mobile Staging Alpha PR ${{ pr }}"
  transient_environment: true
  production_environment: false
  task: staging-alpha
  payload:
    type: mobile
    url: https://staging.alpha.mobile.sentrei.com
mobile-production-beta:
  auto_deploy_on: refs/heads/beta
  environment: "Mobile Production Beta"
  production_environment: true
  task: beta
  payload:
    type: mobile
    url: https://beta.mobile.sentrei.com
mobile-staging-beta:
  environment: "Mobile Staging Beta PR ${{ pr }}"
  transient_environment: true
  production_environment: false
  task: staging-beta
  payload:
    type: mobile
    url: https://staging.beta.mobile.sentrei.com
mobile-production-master:
  auto_deploy_on: refs/heads/master
  environment: "Mobile Production Master"
  production_environment: true
  task: master
  payload:
    type: mobile
    url: https://mobile.sentrei.com
mobile-staging-master:
  environment: "Mobile Staging Master PR ${{ pr }}"
  transient_environment: true
  production_environment: false
  task: staging-master
  payload:
    type: mobile
    url: https://staging.mobile.sentrei.com
web-production-alpha:
  auto_deploy_on: refs/heads/alpha
  environment: "Web Production Alpha"
  production_environment: true
  task: alpha
  payload:
    type: web
    url: https://alpha.sentrei.com
web-staging-alpha:
  environment: "Web Staging Alpha PR ${{ pr }}"
  transient_environment: true
  production_environment: false
  task: staging-alpha
  payload:
    type: web
    url: https://staging.alpha.sentrei.com
web-production-beta:
  auto_deploy_on: refs/heads/beta
  environment: "Web Production Beta"
  production_environment: true
  task: beta
  payload:
    type: web
    url: https://beta.sentrei.com
web-staging-beta:
  environment: "Web Staging Beta PR ${{ pr }}"
  transient_environment: true
  production_environment: false
  task: staging-beta
  payload:
    type: web
    url: https://staging.beta.sentrei.com
web-production-master:
  auto_deploy_on: refs/heads/master
  environment: "Web Production Master"
  production_environment: true
  task: master
  payload:
    type: web
    url: https://sentrei.com
web-staging-master:
  environment: "Web Staging Master PR ${{ pr }}"
  transient_environment: true
  production_environment: false
  task: staging-master
  payload:
    type: web
    url: https://staging.sentrei.com
