- name: "design"
  color: "0366d6"
  description: ""
- name: "github"
  color: "0366d6"
  description: ""
- name: "infrastructure"
  color: "0366d6"
  description: ""
- name: "packages/blog"
  color: "0366d6"
  description: ""
- name: "packages/common"
  color: "0366d6"
  description: ""
- name: "packages/design"
  color: "0366d6"
  description: ""
- name: "packages/docs"
  color: "0366d6"
  description: ""
- name: "packages/functions"
  color: "0366d6"
  description: ""
- name: "packages/fastlane"
  color: "0366d6"
  description: ""
- name: "packages/mobile"
  color: "0366d6"
  description: ""
- name: "packages/ui"
  color: "0366d6"
  description: ""
- name: "packages/web"
  color: "0366d6"
  description: ""
