coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        paths:
          - "lib"
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: true
      test:
        flags:
          - test
flags:
  test:
    paths:
      - test
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
