coverage:
  precision: 3
  status:
    project:
      test:
        flags:
          - test
        target: auto
        threshold: null
        base: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        informational: true
        only_pulls: true
flags:
  test:
    paths:
      - test/
    carryforward: true
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
