coverage:
  status:
    project:
      default: false
      test:
        flags:
          - test
        target: auto
        threshold: 0%
        base: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        informational: true
        only_pulls: true
flags:
  test:
    paths:
      - test/
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
