name: sentrei
description: A new Flutter project.
version: 2.2.5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_crashlytics: ^0.1.3+3
  firebase_performance: ^0.3.1+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
  uses-material-design: true
