name: sentrei
description: A new Flutter project.
version: 2.4.2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.5+3
  firebase_core: ^0.4.0+9
  firebase_database: ^3.1.3
  firebase_crashlytics: ^0.1.3+3
  firebase_dynamic_links: ^0.5.0+11
  firebase_in_app_messaging: ^0.1.1+3
  firebase_performance: ^0.3.1+7
  firebase_remote_config: ^0.3.0+3
  firebase_storage: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
  uses-material-design: true
