pull_request_rules:
  - name: sentrei
    conditions:
      - status-success=Enforcer
    actions:
      delete_head_branch:
        force: true
      merge:
        method: merge
        strict: smart
