pull_request_rules:
  - name: sentrei
    conditions:
      - label=sentrei-auto-pr
    actions:
      delete_head_branch:
        force: true
      merge:
        method: merge
        strict: smart
