ignores:
  [
    "babel-*",
    "image*",
    "next-*",
    "*-loader",
    "@zeit/next-source-maps",
    "jimp",
    "sass",
    "@cypress/*",
    "@istanbuljs/*",
  ]
skip-missing: true
ignore-path: .gitignore
