blank_issues_enabled: true
contact_links:
  - name: Chatops
    url: https://github.com/sentrei/sentrei/issues/368#partial-timeline
    about: chatops
  - name: Contributors
    url: https://github.com/sentrei/sentrei/issues/171#partial-timeline
    about: contributors
  - name: Inspirations
    url: https://github.com/sentrei/sentrei/issues/170#partial-timeline
    about: inspirations
