fastlane_version "2.28.3"

default_platform :android

platform :android do
  desc "Set appicons"
  lane :icon do
    android_appicon(
      appicon_image_file: '../assets/sentrei.png',
      appicon_icon_types: [:launcher],
      appicon_path: 'app/src/main/res/mipmap',
      appicon_filename: 'ic_launcher',
    )
  end

  desc "Submit a new alpha build to firebase"
  lane :alpha do
    add_badge(
      alpha: true,
      dark: true,
      glob: "/app/src/main/res/mipmap-*/ic_launcher*.png",
    )
    gradle(
      task: "bundle",
      flavor: "alpha",
      build_type: "Release"
    )
    firebase_app_distribution(
      groups: "alpha",
      app: "1:280671636932:android:69407d4e605d5e60cd6891",
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      release_notes: ENV['GITHUB_RUN_NUMBER'],
    )
    firebase_test_lab_android(
      project_id: "sentrei-alpha",
      gcloud_service_key_file: "key/alpha/sentrei-alpha.json",
      type: "robo",
      devices: [
        {
          model: "Pixel2",
          version: "29"
        }
      ],
      app_apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
      download_dir: "results",
    )
  end

  desc "Submit a new beta build to firebase"
  lane :beta do
    add_badge(
      dark: true,
      glob: "/app/src/main/res/mipmap-*/ic_launcher*.png",
    )
    gradle(
      task: "bundle",
      flavor: "beta",
      build_type: "Release"
    )
    firebase_app_distribution(
      groups: "beta",
      app: "1:258612152633:android:0344f8ed2ff95c50ff40e8",
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      release_notes: ENV['GITHUB_RUN_NUMBER'],
    )
    firebase_test_lab_android(
      project_id: "sentrei-beta",
      gcloud_service_key_file: "key/beta/sentrei-beta.json",
      type: "robo",
      devices: [
        {
          model: "Pixel2",
          version: "29"
        }
      ],
      app_apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
      download_dir: "results",
    )
  end

  desc "Submit a new master build to firebase"
  lane :master do
    gradle(
      task: "bundle",
      flavor: "master",
      build_type: "Release"
    )
    firebase_app_distribution(
      groups: "master",
      app: "1:721847679884:android:1935b57831163cda5bb4a9",
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      release_notes: ENV['GITHUB_RUN_NUMBER'],
    )
    firebase_test_lab_android(
      project_id: "sentrei-master",
      gcloud_service_key_file: "key/master/sentrei-master.json",
      type: "robo",
      devices: [
        {
          model: "Pixel2",
          version: "29"
        }
      ],
      app_apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
      download_dir: "results",
    )
  end

  lane :test do |options|
    if options[:alpha]
      gradle(
        task: "bundle",
        flavor: "alpha",
        build_type: "Release"
      )
      firebase_test_lab_android(
        project_id: "sentrei-alpha",
        gcloud_service_key_file: "key/alpha/sentrei-alpha.json",
        type: "robo",
        devices: [
          {
            model: "Pixel2",
            version: "29"
          }
        ],
        app_apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
        github_owner: "sentrei",
        github_repository: "sentrei",
        github_pr_number: ENV["PR_NUMBER"],
        github_api_token: ENV["GITHUB_TOKEN"],
        download_dir: "results",
      )
    end
    if options[:beta]
      gradle(
        task: "bundle",
        flavor: "beta",
        build_type: "Release"
      )
      firebase_test_lab_android(
        project_id: "sentrei-beta",
        gcloud_service_key_file: "key/beta/sentrei-beta.json",
        type: "robo",
        devices: [
          {
            model: "Pixel2",
            version: "29"
          }
        ],
        app_apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
        github_owner: "sentrei",
        github_repository: "sentrei",
        github_pr_number: ENV["PR_NUMBER"],
        github_api_token: ENV["GITHUB_TOKEN"],
        download_dir: "results",
      )
    end
    if options[:master]
      gradle(
        task: "bundle",
        flavor: "master",
        build_type: "Release"
      )
      firebase_test_lab_android(
        project_id: "sentrei-master",
        gcloud_service_key_file: "key/master/sentrei-master.json",
        type: "robo",
        devices: [
          {
            model: "Pixel2",
            version: "29"
          }
        ],
        app_apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
        github_owner: "sentrei",
        github_repository: "sentrei",
        github_pr_number: ENV["PR_NUMBER"],
        github_api_token: ENV["GITHUB_TOKEN"],
        download_dir: "results",
      )
    end
  end

  lane :local do |options|
    if options[:alpha]
      gradle(
        task: "bundle",
        flavor: "alpha",
        build_type: "Release"
      )
    end
    if options[:beta]
      gradle(
        task: "bundle",
        flavor: "beta",
        build_type: "Release"
      )
    end
    if options[:master]
      gradle(
        task: "bundle",
        flavor: "master",
        build_type: "Release"
      )
    end
  end
end
