fastlane_version "2.28.3"

default_platform :android

desc "Bump version code"
private_lane :bump_version_code do |options|
  g = google_play_track_version_codes
  gb = google_play_track_version_codes(track: "beta")
  ga = google_play_track_version_codes(track: "alpha")
  max_value = [g[0].to_i, gb[0].to_i, ga[0].to_i].max
  version_updated = max_value + 1
  increment_version_code(
    gradle_file_path: "app/build.gradle",
    version_code: version_updated.to_i
  )
end

platform :android do
  desc "Set appicons"
  lane :icon do
    android_appicon(
      appicon_image_file: "../assets/sentrei.png",
      appicon_icon_types: [:launcher],
      appicon_path: "app/src/main/res/mipmap",
      appicon_filename: "ic_launcher",
    )
  end

  desc "Submit a new alpha build to firebase"
  lane :alpha do
    bump_version_code()
    add_badge(
      alpha: true,
      dark: true,
      glob: "/app/src/main/res/mipmap-*/ic_launcher*.png",
    )
    gradle(
      task: "assemble",
      flavor: "alpha",
      build_type: "Release",
    )
    gradle(
      task: "bundle",
      flavor: "alpha",
      build_type: "Release",
    )
    firebase_app_distribution(
      groups: "alpha",
      app: "1:280671636932:android:69407d4e605d5e60cd6891",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      release_notes: ENV["GITHUB_RUN_NUMBER"],
      apk_path: "../build/app/outputs/apk/alpha/release/app-alpha-release.apk",
    )
    upload_to_play_store(
      track: "internal",
      track_promote_to: "alpha",
      release_status: "draft",
      aab: "../build/app/outputs/bundle/alphaRelease/app-alpha-release.aab",
      skip_upload_screenshots: true,
      skip_upload_images: true,
    )
    firebase_test_lab_android(
      project_id: "sentrei-alpha",
      gcloud_service_key_file: "key/alpha/sentrei-alpha.json",
      type: "robo",
      devices: [
        {
          model: "Pixel2",
          version: "29"
        }
      ],
      app_apk: "../build/app/outputs/apk/alpha/release/app-alpha-release.apk",
      download_dir: "results",
    )
  end

  desc "Submit a new beta build to firebase"
  lane :beta do
    bump_version_code()
    add_badge(
      dark: true,
      glob: "/app/src/main/res/mipmap-*/ic_launcher*.png",
    )
    gradle(
      task: "assemble",
      flavor: "beta",
      build_type: "Release",
    )
    gradle(
      task: "bundle",
      flavor: "beta",
      build_type: "Release",
    )
    firebase_app_distribution(
      groups: "beta",
      app: "1:258612152633:android:c60ef5d4f54ab97eff40e8",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      release_notes: ENV["GITHUB_RUN_NUMBER"],
      apk_path: "../build/app/outputs/apk/beta/release/app-beta-release.apk",
    )
    upload_to_play_store(
      track: "alpha",
      track_promote_to: "beta",
      release_status: "draft",
      aab: "../build/app/outputs/bundle/betaRelease/app-beta-release.aab",
      skip_upload_screenshots: true,
      skip_upload_images: true,
    )
    firebase_test_lab_android(
      project_id: "sentrei-beta",
      gcloud_service_key_file: "key/beta/sentrei-beta.json",
      type: "robo",
      devices: [
        {
          model: "Pixel2",
          version: "29"
        }
      ],
      app_apk: "../build/app/outputs/apk/beta/release/app-beta-release.apk",
      download_dir: "results",
    )
  end

  desc "Submit a new master build to firebase"
  lane :master do
    bump_version_code()
    gradle(
      task: "assemble",
      flavor: "master",
      build_type: "Release",
    )
    gradle(
      task: "bundle",
      flavor: "master",
      build_type: "Release",
    )
    firebase_app_distribution(
      groups: "master",
      app: "1:721847679884:android:1935b57831163cda5bb4a9",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      release_notes: ENV["GITHUB_RUN_NUMBER"],
      apk_path: "../build/app/outputs/apk/master/release/app-master-release.apk",
    )
    upload_to_play_store(
      track: "beta",
      track_promote_to: "production",
      release_status: "draft",
      aab: "../build/app/outputs/bundle/masterRelease/app-master-release.aab",
      skip_upload_screenshots: true,
      skip_upload_images: true,
    )
    firebase_test_lab_android(
      project_id: "sentrei-master",
      gcloud_service_key_file: "key/master/sentrei-master.json",
      type: "robo",
      devices: [
        {
          model: "Pixel2",
          version: "29"
        }
      ],
      app_apk: "../build/app/outputs/apk/master/release/app-master-release.apk",
      download_dir: "results",
    )
  end

  lane :test do |options|
    if options[:alpha]
      gradle(
        task: "bundle",
        flavor: "alpha",
        build_type: "Release"
      )
      firebase_test_lab_android(
        project_id: "sentrei-alpha",
        gcloud_service_key_file: "key/alpha/sentrei-alpha.json",
        type: "robo",
        devices: [
          {
            model: "Pixel2",
            version: "29"
          }
        ],
        app_apk: "../build/app/outputs/apk/alpha/release/app-alpha-release.apk",
        github_owner: "sentrei",
        github_repository: "sentrei",
        github_pr_number: ENV["PR_NUMBER"],
        github_api_token: ENV["GITHUB_TOKEN"],
        download_dir: "results",
      )
    end
    if options[:beta]
      gradle(
        task: "bundle",
        flavor: "beta",
        build_type: "Release"
      )
      firebase_test_lab_android(
        project_id: "sentrei-beta",
        gcloud_service_key_file: "key/beta/sentrei-beta.json",
        type: "robo",
        devices: [
          {
            model: "Pixel2",
            version: "29"
          }
        ],
        app_apk: "../build/app/outputs/apk/beta/release/app-beta-release.apk",
        github_owner: "sentrei",
        github_repository: "sentrei",
        github_pr_number: ENV["PR_NUMBER"],
        github_api_token: ENV["GITHUB_TOKEN"],
        download_dir: "results",
      )
    end
    if options[:master]
      gradle(
        task: "bundle",
        flavor: "master",
        build_type: "Release"
      )
      firebase_test_lab_android(
        project_id: "sentrei-master",
        gcloud_service_key_file: "key/master/sentrei-master.json",
        type: "robo",
        devices: [
          {
            model: "Pixel2",
            version: "29"
          }
        ],
        app_apk: "../build/app/outputs/apk/master/release/app-master-release.apk",
        github_owner: "sentrei",
        github_repository: "sentrei",
        github_pr_number: ENV["PR_NUMBER"],
        github_api_token: ENV["GITHUB_TOKEN"],
        download_dir: "results",
      )
    end
  end

  lane :local do |options|
    if options[:alpha]
      gradle(
        task: "assemble",
        flavor: "alpha",
        build_type: "Release",
      )
      gradle(
        task: "bundle",
        flavor: "alpha",
        build_type: "Release",
      )
    end
    if options[:beta]
      gradle(
        task: "assemble",
        flavor: "beta",
        build_type: "Release",
      )
      gradle(
        task: "bundle",
        flavor: "beta",
        build_type: "Release",
      )
    end
    if options[:master]
      gradle(
        task: "assemble",
        flavor: "master",
        build_type: "Release",
      )
      gradle(
        task: "bundle",
        flavor: "master",
        build_type: "Release",
      )
    end
  end
end
