import 'package:flutter/material.dart';

/// Reference: https://github.com/simplezhli/flutter_deer/blob/a89b6cc4edb0197a4dfd0f830c54b873015d077f/lib/res/colors.dart
class Colours {
  static const Color app_main = Color(0xFF4688FA);
  static const Color app_main_dark = Color(0xFF3F7AE0);
  static const Color bg_color = Color(0xfff1f1f1);
  static const Color bg_color_dark = Color(0xFF18191A);
  static const Color bg_color_light = Colors.white;
  static const Color bg_gray = Color(0xFFF6F6F6);
  static const Color bg_gray_ = Color(0xFFFAFAFA);
  static const Color bg_gray__dark = Color(0xFF242526);
  static const Color bg_gray_dark = Color(0xFF1F1F1F);
  static const Color black = Color(0xff353535);
  static const Color black_opaque = Colors.black12;
  static const Color blue = Color(0xffabecd6);
  static const Color blue_deep = Color(0xffA8CBFD);
  static const Color blue_light = Color(0xffAED3EA);
  static const Color button_disabled = Color(0xFF96BBFA);
  static const Color button_disabled_dark = Color(0xFF83A5E0);
  static const Color button_text_dark = Color(0xFFF2F2F2);
  static const Color gray = Color(0xff434343);
  static const Color green = Color(0xffc7e5b4);
  static const Color line = Color(0xFFEEEEEE);
  static const Color line_dark = Color(0xFF3A3C3D);
  static const Color material_bg = Color(0xFFFFFFFF);
  static const Color material_bg_dark = Color(0xFF303233);
  static const Color material_bg_light = Colors.white;
  static const Color orange = Color(0xffffc2a1);
  static const Color orange_light = Color(0xffFFC3A0);
  static const Color purple = Color(0xffccc3fc);
  static const Color purple_dark = Color(0xFF5B16D0);
  static const Color red = Color(0xffF2A7B3);
  static const Color red_dark = Color(0xffF2A7B3);
  static const Color red_light = Color(0xffffb1bb);
  static const Color text = Color(0xFF333333);
  static const Color text_black = Color(0xFF353535);
  static const Color text_black_light = Color(0xFF34323D);
  static const Color text_dark = Color(0xFFB8B8B8);
  static const Color text_disabled = Color(0xFFD4E2FA);
  static const Color text_disabled_dark = Color(0xFFCEDBF2);
  static const Color text_gray = Color(0xFF999999);
  static const Color text_gray_c = Color(0xFFcccccc);
  static const Color text_gray_dark = Color(0xFF666666);
  static const Color unselected_item_color = Color(0xffbfbfbf);
  static const Color unselected_item_color_dark = Color(0xFF4D4D4D);
  static const Color white = Colors.white;
  static const Color yellow = Color(0xfffbed96);
  static const Color yellow_light = Color(0xfffbed96);
}
