version: 1
update_configs:
  - package_manager: "github_actions"
    directory: "."
    update_schedule: "daily"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
    default_reviewers:
      - shunkakinoki
  - package_manager: "javascript"
    directory: "."
    update_schedule: "live"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
    default_reviewers:
      - shunkakinoki
  - package_manager: "python"
    directory: "."
    update_schedule: "live"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
    default_reviewers:
      - shunkakinoki
  - package_manager: "ruby:bundler"
    directory: "sentrei/mobile/android"
    update_schedule: "daily"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
    default_reviewers:
      - shunkakinoki
  - package_manager: "ruby:bundler"
    directory: "sentrei/mobile/ios"
    update_schedule: "daily"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
    default_reviewers:
      - shunkakinoki
