name: Auto Approve
on: pull_request
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        if: github.actor == 'shunkakinoki'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.createReview({
              pull_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: 'APPROVE',
            })
      - uses: actions/github-script@0.9.0
        if: |
          github.actor == 'github-actions[bot]' ||
          github.actor == 'dependabot[bot]' ||
          github.actor == 'dependabot-preview[bot]' ||
          github.actor == 'imgbot' ||
          github.actor == 'imgbot[bot]'
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            github.pulls.createReview({
              pull_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: 'APPROVE',
            })
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies with yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install
      - name: Run yarn fix
        run: |
          yarn run fix
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Shun Kakinoki'
          git config --global user.email 'shunkakinoki@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "[sentrei-auto-fix]"
          git push
  ready:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        if: |
          github.event.pull_request != null && contains(toJson(github.event.pull_request.title), '[sentrei-auto-pr]') && (github.actor == 'shunkakinoki') ||
          github.actor == 'dependabot[bot]' ||
          github.actor == 'dependabot-preview[bot]' ||
          github.actor == 'mergify[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          msg: "/ready"
