name: Auto Merge
on:
  check_suite:
    types:
      - completed
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          MERGE_LABELS: "ready-to-merge,sentrei-auto-pr,!packages/functions,!packages/ui,!packages/web"
          UPDATE_LABELS: "ready-to-merge,sentrei-auto-pr"
