name: Auto Merge
on:
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked
  deployment: {}
  deployment_status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          MERGE_LABELS: "ready-to-merge,!fastlane,!ui,!web"
          MERGE_RETRIES: "300"
          MERGE_RETRY_SLEEP: "1000"
