# name: Auto-merge
# on:
#   pull_request:
#     types:
#       - labeled
#       - unlabeled
#       - synchronize
#   pull_request_review:
#     types:
#       - submitted
#   check_suite:
#     types:
#       - completed
#   status: {}
# jobs:
#   auto-merge:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: pascalgn/automerge-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           MERGE_LABELS: "ready-to-merge,sentrei-auto-pr,!packages/functions,!packages/ui,!packages/web"
#           UPDATE_LABELS: "ready-to-merge,sentrei-auto-pr"
