name: Auto Merge
on:
  check_suite:
    types: [completed]
  repository_dispatch:
    types: [enforcer-cmd]
  pull_request:
    types:
      [
        opened,
        edited,
        labeled,
        ready_for_review,
        reopened,
        synchronize,
        unlabeled,
      ]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          MERGE_LABELS: "ready-to-merge,!fastlane,!ui,!web"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"
