name: Auto Approve
on: pull_request
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: |
          github.actor == 'shunkakinoki' ||
          github.actor == 'github-actions[bot]' ||
          github.actor == 'dependabot[bot]' ||
          github.actor == 'dependabot-preview[bot]' ||
          github.actor == 'imgbot' ||
          github.actor == 'imgbot[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  ready:
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        if: |
          github.event.pull_request != null && contains(toJson(github.event.pull_request.title), '[sentrei-auto-pr]') && (github.actor == 'shunkakinoki') ||
          github.actor == 'dependabot[bot]' ||
          github.actor == 'dependabot-preview[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          msg: "/ready"
