name: CLA
on: pull_request
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
        uses: cla-assistant/github-action@v1.3.0-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: "signatures/version1/cla.json"
          path-To-cladocument: "https://github.com/sentrei/sentrei/blob/master/README.md"
          branch: "master"
          whitelist: dependabot[bot],github-actions[bot]
          empty-commit-flag: false
          blockchain-storage-flag: false
