name: Deployment
on: deployment
env:
  flutter_channel: "stable"
  flutter_version: "1.12.13+hotfix.9"
jobs:
  design:
    if: github.event.deployment.payload.type == 'design'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - name: Cache node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-v1-
      - name: Install dependencies with yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile --ignore-engines
      - name: Deployment pending
        uses: deliverybot/deployment-status@master
        with:
          environment-url: ${{ github.event.deployment.payload.url }}
          state: pending
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to firebase
        working-directory: sentrei/design
        run: |
          yarn run ${{ github.event.deployment.task }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deployment success
        if: success()
        uses: deliverybot/deployment-status@master
        with:
          environment-url: ${{ github.event.deployment.payload.url }}
          state: success
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deployment failure
        if: failure()
        uses: deliverybot/deployment-status@master
        with:
          environment-url: ${{ github.event.deployment.payload.url }}
          state: failure
          token: ${{ secrets.GITHUB_TOKEN }}
  mobile:
    if: github.event.deployment.payload.type == 'mobile'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies with yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile --ignore-engines
      - name: Generate docs
        working-directory: sentrei/mobile
        run: |
          flutter pub global activate dartdoc
          flutter pub global run dartdoc:dartdoc --exclude 'dart:async,dart:collection,dart:convert,dart:core,dart:developer,dart:io,dart:isolate,dart:math,dart:typed_data,dart:ui,dart:ffi,dart:html,dart:js,dart:js_util'
      - name: Deployment pending
        uses: deliverybot/deployment-status@master
        with:
          environment-url: ${{ github.event.deployment.payload.url }}
          state: pending
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to firebase
        working-directory: sentrei/mobile
        run: |
          yarn run ${{ github.event.deployment.task }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deployment success
        if: success()
        uses: deliverybot/deployment-status@master
        with:
          environment-url: ${{ github.event.deployment.payload.url }}
          state: success
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deployment failure
        if: failure()
        uses: deliverybot/deployment-status@master
        with:
          environment-url: ${{ github.event.deployment.payload.url }}
          state: failure
          token: ${{ secrets.GITHUB_TOKEN }}
  web:
    if: github.event.deployment.payload.type == 'web'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Cache node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-v1-
      - name: Install dependencies with yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile --ignore-engines
      - name: Deployment pending
        uses: deliverybot/deployment-status@master
        with:
          environment-url: ${{ github.event.deployment.payload.url }}
          state: pending
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to firebase
        working-directory: sentrei/web
        run: |
          yarn run ${{ github.event.deployment.task }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deployment success
        if: success()
        uses: deliverybot/deployment-status@master
        with:
          environment-url: ${{ github.event.deployment.payload.url }}
          state: success
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deployment failure
        if: failure()
        uses: deliverybot/deployment-status@master
        with:
          environment-url: ${{ github.event.deployment.payload.url }}
          state: failure
          token: ${{ secrets.GITHUB_TOKEN }}
