name: Docs
on: deployment
env:
  flutter_channel: "stable"
  flutter_version: "1.12.13+hotfix.9"
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.branch.outputs.branch }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies with yarn
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: sentrei/mobile
        run: |
          yarn install --frozen-lockfile
      - name: Generate docs
        working-directory: sentrei/mobile
        run: |
          flutter pub global activate dartdoc
          flutter pub global run dartdoc:dartdoc --exclude 'dart:async,dart:collection,dart:convert,dart:core,dart:developer,dart:io,dart:isolate,dart:math,dart:typed_data,dart:ui,dart:ffi,dart:html,dart:js,dart:js_util'
      - name: Deployment pending
        uses: deliverybot/deployment-status@master
        with:
          state: pending
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to firebase
        working-directory: sentrei/mobile
        run: |
          yarn run master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deployment success
        if: success()
        uses: deliverybot/deployment-status@master
        with:
          state: success
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deployment failure
        if: failure()
        uses: deliverybot/deployment-status@master
        with:
          state: failure
          token: ${{ secrets.GITHUB_TOKEN }}
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
