name: Docs
on:
  push:
    branches:
      - alpha
      - beta
      - master
  repository_dispatch:
    types: [docs-cmd]
env:
  flutter_channel: "stable"
  flutter_version: "1.12.13+hotfix.8"
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        if: github.event_name == 'push'
        id: branch
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Checkout
        if: github.event_name == 'push'
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.branch.outputs.branch }}
      - name: Checkout
        if: github.event.client_payload.pull_request != null
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies with yarn
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: sentrei
        run: |
          yarn install
      - name: Generate docs
        working-directory: sentrei
        run: |
          flutter pub global activate dartdoc
          flutter pub global run dartdoc:dartdoc --exclude 'dart:async,dart:collection,dart:convert,dart:core,dart:developer,dart:io,dart:isolate,dart:math,dart:typed_data,dart:ui,dart:ffi,dart:html,dart:js,dart:js_util'
      - name: Deploy to firebase
        if: github.event.client_payload.pull_request != null
        working-directory: sentrei
        run: |
          yarn run ${{ github.event.client_payload.pull_request.base.ref }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to firebase
        if: github.event_name == 'push'
        working-directory: sentrei
        run: |
          yarn run ${{ steps.branch.outputs.branch }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Comment url
        if: github.event.client_payload.pull_request != null
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
          edit-mode: replace
          body: |
            Doc updated on https://${{ github.event.client_payload.pull_request.base.ref }}.docs.sentrei.com
