name: Docs
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, edited]
  repository_dispatch:
    types: [test-cmd]
env:
  flutter_channel: "stable"
  flutter_version: "1.12.13+hotfix.8"
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract PR number
        run: |
          echo ::set-env name=PR_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      - id: change
        run: |
          git fetch --quiet
          if git diff --quiet origin/${{ github.event.pull_request.head.ref }}..origin/${{ github.event.pull_request.base.ref }} -- sentrei/lib; then
            echo ::set-output name=changed::false && exit 0
          else
            echo ::set-output name=changed::true && exit 0
          fi
      - name: Cache flutter
        if: steps.change.outputs.changed == 'true'
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-v1-${{ runner.os }}-${{ env.flutter_version }}
          restore-keys: |
            flutter-v1-${{ runner.os }}-
      - name: Cache pub
        if: steps.change.outputs.changed == 'true'
        uses: actions/cache@v1
        with:
          path: ~/.pub-cache
          key: pub-v1-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            pub-v1-
      - name: Install flutter
        if: steps.change.outputs.changed == 'true'
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - name: Generate docs
        if: steps.change.outputs.changed == 'true'
        working-directory: sentrei
        run: |
          flutter pub global activate dartdoc
          flutter pub global run dartdoc:dartdoc --exclude 'dart:async,dart:collection,dart:convert,dart:core,dart:developer,dart:io,dart:isolate,dart:math,dart:typed_data,dart:ui,dart:ffi,dart:html,dart:js,dart:js_util'
