name: Dummy
on: push
jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  ui:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  web:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
