name: Figma
on:
  repository_dispatch:
    types: [figma-cmd]
jobs:
  figma:
    runs-on: ubuntu-latest
    steps:
      - uses: primer/figma-action@v1.0.0-alpha.2
        with:
          args: "format=png outputDir=design/figma/"
        env:
          FIGMA_FILE_URL: "https://www.figma.com/file/FcE7ACUUJAey0gspwpFN48/colours"
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
