name: Fix
on:
  repository_dispatch:
    types: [fix-cmd]
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies with yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install
      - name: Run yarn fix
        run: |
          yarn run fix
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "[sentrei-auto-fix]" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.event.client_payload.pull_request.head.ref }}
          force: false
          github_token: ${{ secrets.ACCESS_TOKEN }}
      - name: Comment fix completed
        if: github.event.client_payload.pull_request != null
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
          edit-mode: replace
          body: |
            `yarn run fix` completed
