name: Fix
on:
  repository_dispatch:
    types: [fix-cmd]
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies with yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install
      - name: Run yarn fix
        run: |
          yarn run fix
      - name: Git auto push
        run: |
          git add -A && git commit -m "chore: sentrei-auto-fix" && git push
      - name: Comment fix completed
        if: github.event.client_payload.pull_request != null
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
          edit-mode: replace
          body: |
            `yarn run fix` completed
