name: Flutter
on: pull_request
jobs:
  flutter:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache flutter
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: flutter-v1
      - name: Cache pub
        uses: actions/cache@v1
        with:
          path: ~/.pub-cache
          key: pub-v1-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            pub-v1-
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.13+hotfix.8"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
          name: sentrei
          fail_ci_if_error: true
