name: Flutter
on: pull_request
env:
  flutter_channel: "stable"
  flutter_version: "1.12.13+hotfix.9"
jobs:
  change:
    runs-on: ubuntu-latest
    outputs:
      change: ${{ steps.change.outputs.change }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: change
        run: |
          git fetch --quiet
          if git diff --quiet origin/${{ github.event.pull_request.head.ref }}..origin/${{ github.event.pull_request.base.ref }} -- sentrei/mobile/lib; then
            echo ::set-output name=change::false && exit 0
          else
            echo ::set-output name=change::true && exit 0
          fi
  flutter:
    runs-on: ubuntu-latest
    if: ${{ needs.change.outputs.change }} == 'true'
    needs: change
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract PR number
        run: |
          echo ::set-env name=PR_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      - id: change
        run: |
          git fetch --quiet
          if git diff --quiet origin/${{ github.event.pull_request.head.ref }}..origin/${{ github.event.pull_request.base.ref }} -- sentrei/mobile/lib; then
            echo ::set-output name=changed::false && exit 0
          else
            echo ::set-output name=changed::true && exit 0
          fi
      - name: Install flutter
        if: steps.change.outputs.changed == 'true'
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - if: steps.change.outputs.changed == 'true'
        working-directory: sentrei/mobile
        run: |
          flutter pub get
      - if: steps.change.outputs.changed == 'true'
        working-directory: sentrei/mobile
        run: |
          flutter analyze
      - if: steps.change.outputs.changed == 'true'
        working-directory: sentrei/mobile
        run: |
          flutter test --coverage
      - name: Upload coverage to Codecov
        if: steps.change.outputs.changed == 'true'
        uses: codecov/codecov-action@v1
        with:
          file: sentrei/mobile/coverage/lcov.info
          name: sentrei
          fail_ci_if_error: true
          flags: mobile
