name: Flutter
on: pull_request
env:
  flutter_channel: "stable"
  flutter_version: "1.12.13+hotfix.8"
jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract PR number
        run: |
          echo ::set-env name=PR_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      - id: change
        run: |
          git fetch --quiet
          if git diff --quiet origin/${{ github.event.pull_request.head.ref }}..origin/${{ github.event.pull_request.base.ref }} -- sentrei/lib; then
            echo ::set-output name=changed::false && exit 0
          else
            echo ::set-output name=changed::true && exit 0
          fi
      - name: Install flutter
        if: steps.change.outputs.changed == 'true'
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - if: steps.change.outputs.changed == 'true'
        working-directory: sentrei
        run: |
          flutter pub get
      - if: steps.change.outputs.changed == 'true'
        working-directory: sentrei
        run: |
          flutter analyze
          flutter test --coverage
      - name: Upload coverage to Codecov
        if: steps.change.outputs.changed == 'true'
        uses: codecov/codecov-action@v1
        with:
          file: sentrei/coverage/lcov.info
          name: sentrei
          fail_ci_if_error: true
          flags: test
