name: Flutter
on: pull_request
env:
  flutter_channel: "stable"
  flutter_version: "1.12.13+hotfix.8"
jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract PR number
        run: |
          echo ::set-env name=PR_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      - run: |
          git diff --name-status ${{ github.event.pull_request.head.ref }}..${{ github.event.pull_request.base.ref }}
      - name: Cache flutter
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-v1-${{ runner.os }}-${{ env.flutter_version }}
          restore-keys: |
            flutter-v1-${{ runner.os }}-
      - name: Cache pub
        uses: actions/cache@v1
        with:
          path: ~/.pub-cache
          key: pub-v1-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            pub-v1-
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - run: |
          cd sentrei
          flutter pub get
          flutter analyze
          flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: sentrei/coverage/lcov.info
          name: sentrei
          fail_ci_if_error: true
          flags: test
