name: LGTM
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  repository_dispatch:
    types: [lgtm-cmd]
jobs:
  comment:
    if: github.event.client_payload != null
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: ${{ github.event.client_payload.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ready-to-merge'],
            })
      - uses: actions/github-script@0.9.0
        if: github.actor != 'shunkakinoki'
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            github.pulls.createReview({
              pull_number: ${{ github.event.client_payload.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: 'APPROVE',
            })
  reaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-lgtm-reaction@
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          trigger: '["^/lgtm$"]'
