name: LGTM
on:
  repository_dispatch:
    types: [lgtm-cmd]
jobs:
  lgtm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: ${{ github.event.client_payload.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ready-to-merge'],
            })
      - uses: actions/github-script@0.9.0
        if: github.actor != 'shunkakinoki'
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            github.pulls.createReview({
              pull_number: ${{ github.event.client_payload.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: 'APPROVE',
            })
      - uses: micnncim/action-lgtm-reaction@v0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          trigger: '["/lgtm"]'
