name: Mobile
on:
  pull_request:
    paths:
      - "packages/mobile/**"
env:
  flutter_channel: "stable"
  flutter_version: "1.12.13+hotfix.9"
jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - working-directory: packages/mobile
        run: |
          flutter pub get
      - working-directory: packages/mobile
        run: |
          flutter analyze
      - working-directory: packages/mobile
        run: |
          flutter test --coverage
      - uses: codecov/codecov-action@v1
        continue-on-error: true
        with:
          file: packages/mobile/coverage/lcov.info
          name: sentrei
          fail_ci_if_error: true
          flags: mobile
