name: Mobile
on: pull_request
env:
  flutter_channel: "stable"
  flutter_version: "1.12.13+hotfix.9"
jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: change
        run: |
          git fetch --quiet
          if git diff --quiet origin/${{ github.event.pull_request.head.ref }}..origin/${{ github.event.pull_request.base.ref }} -- packages/mobile; then
            echo ::set-output name=changed::'false' && exit 0
          else
            echo ::set-output name=changed::'true' && exit 0
          fi
      - if: steps.change.outputs.changed == 'true'
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}
      - if: steps.change.outputs.changed == 'true'
        working-directory: packages/mobile
        run: |
          flutter pub get
      - if: steps.change.outputs.changed == 'true'
        working-directory: packages/mobile
        run: |
          flutter analyze
      - if: steps.change.outputs.changed == 'true'
        working-directory: packages/mobile
        run: |
          flutter test --coverage
      - if: steps.change.outputs.changed == 'true'
        uses: codecov/codecov-action@v1
        with:
          file: packages/mobile/coverage/lcov.info
          name: sentrei
          fail_ci_if_error: true
          flags: mobile
