name: Release
on:
  push:
    branches:
      - alpha
      - beta
      - master
env:
  flutter_channel: "stable"
  flutter_version: "1.12.13+hotfix.9"
jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo $GITHUB_CONTEXT
      - id: branch
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: context
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          always-auth: false
          node-version: "14.x"
          registry-url: https://registry.npmjs.org
          scope: "@sentrei"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - id: cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            ${{ steps.yarn-cache-path.outputs.dir }}
          key: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}--
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          version=$(node -pe "require('./package.json').version")
          sed -i -e "s/^version: .*/version: $version/" packages/mobile/pubspec.yaml
          for i in $(find packages -name package.json); do
            sed -i -e "s/^  \"version\": .*/  \"version\": \"$version\",/" $i
            cat $i
          done
      - run: |
          npm whoami
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git stash && yarn run publish && git stash pop || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: |
          yarn run fix
      - uses: peter-evans/create-pull-request@v2
        with:
          branch-suffix: short-commit-hash
          token: ${{ secrets.ACCESS_TOKEN }}
          title: "chore: [sentrei-auto-pr]"
        env:
          HUSKY_SKIP_HOOKS: 1
  design:
    if: contains(toJson(github.event.commits), '[sentrei-auto-pr]') == true
    runs-on: ubuntu-latest
    needs: context
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: deploy-cmd
          client-payload: '{"base": "${{ needs.context.outputs.branch }}", "branch": "${{ needs.context.outputs.branch }}", "comment_id": "", "environment": "Production", "event_name": "design", "pull_request_number": "", "release": "true", "task": "design", "tag": "design", "url_prefix": ""}'
  fastlane:
    if: contains(toJson(github.event.commits), '[sentrei-auto-pr]') == true
    runs-on: ubuntu-latest
    needs: context
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: deploy-cmd
          client-payload: '{"base": "${{ needs.context.outputs.branch }}", "branch": "${{ needs.context.outputs.branch }}", "comment_id": "", "environment": "Production", "event_name": "fastlane", "pull_request_number": "", "release": "false", "task": "fastlane", "tag": "fastlane", "url_prefix": ""}'
  mobile:
    if: contains(toJson(github.event.commits), '[sentrei-auto-pr]') == true
    runs-on: ubuntu-latest
    needs: context
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: deploy-cmd
          client-payload: '{"base": "${{ needs.context.outputs.branch }}", "branch": "${{ needs.context.outputs.branch }}", "comment_id": "", "environment": "Production", "event_name": "mobile", "pull_request_number": "", "release": "true", "task": "${{ needs.context.outputs.branch }}", "tag": "${{ needs.context.outputs.branch }}", "url_prefix": "${{ needs.context.outputs.branch }}."}'
  ui:
    if: contains(toJson(github.event.commits), '[sentrei-auto-pr]') == true
    runs-on: ubuntu-latest
    needs: context
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: deploy-cmd
          client-payload: '{"base": "${{ needs.context.outputs.branch }}", "branch": "${{ needs.context.outputs.branch }}", "comment_id": "", "environment": "Production", "event_name": "ui", "pull_request_number": "", "release": "true", "task": "ui", "tag": "ui", "url_prefix": ""}'
  web:
    if: contains(toJson(github.event.commits), '[sentrei-auto-pr]') == true
    runs-on: ubuntu-latest
    needs: context
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: deploy-cmd
          client-payload: '{"base": "${{ needs.context.outputs.branch }}", "branch": "${{ needs.context.outputs.branch }}", "comment_id": "", "environment": "Production", "event_name": "web", "pull_request_number": "", "release": "true", "task": "${{ needs.context.outputs.branch }}", "tag": "${{ needs.context.outputs.branch }}", "url_prefix": "${{ needs.context.outputs.branch }}."}'
