name: Release
on:
  push:
    branches:
      - alpha
      - beta
      - master
  repository_dispatch:
    types: [release-cmd]
env:
  flutter_channel: "stable"
  flutter_version: "1.12.13+hotfix.9"
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT
  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Cache node modules
        id: yarn
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-v1-
      - name: Install dependencies with yarn
        if: steps.yarn.outputs.cache-hit != 'true'
        run: |
          yarn install
      - name: Extract branch name
        id: branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Release
        run: |
          yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore yarn.lock
        run: |
          git restore yarn.lock
      - name: Refactor pubspec.yaml
        run: |
          version=$(node -pe "require('./package.json').version")
          sed -i -e "s/^version: .*/version: $version/" sentrei/mobile/pubspec.yaml
      - name: Run yarn fix
        run: |
          yarn run fix
      - name: Publish
        run: |
          git pull --tags
          git stash && yarn run publish && git stash pop || true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create a pull request if updated
        uses: peter-evans/create-pull-request@v2
        with:
          branch-suffix: short-commit-hash
          token: ${{ secrets.ACCESS_TOKEN }}
          title: "chore: [sentrei-auto-pr]"
        env:
          HUSKY_SKIP_HOOKS: 1
      - name: Dispatch fastlane event
        if: contains(toJson(github.event.commits), '[sentrei-auto-pr]') == true
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: fastlane-cmd
          client-payload: '{"branch": "${{ steps.branch.outputs.branch }}", "event_name": "release", "release": "false"}'
  fastlane:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch fastlane event
        if: github.event.client_payload != null
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: fastlane-cmd
          client-payload: '{"branch": "${{ github.event.client_payload.slash_command.arg1 }}", "event_name": "release", "release": "true"}'
