name: Staging
on:
  repository_dispatch:
    types: [staging-cmd]
jobs:
  design:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: deploy-cmd
          client-payload: '{"base": "${{ github.event.client_payload.pull_request.base.ref }}", "branch": "${{ github.event.client_payload.pull_request.head.ref }}", "environment": "staging", "event_name": "${{ github.event.client_payload.slash_command.arg1 }}", "pull_request_number": "${{ github.event.client_payload.pull_request.number }}", "release": "false", "task": "staging:design", "url_prefix": "staging."}'
  mobile:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: deploy-cmd
          client-payload: '{"base": "${{ github.event.client_payload.pull_request.base.ref }}", "branch": "${{ github.event.client_payload.pull_request.head.ref }}", "environment": "staging", "event_name": "${{ github.event.client_payload.slash_command.arg1 }}", "pull_request_number": "${{ github.event.client_payload.pull_request.number }}", "release": "false", "task": "staging:${{ github.event.client_payload.pull_request.base.ref }}", "url_prefix": "staging.${{ github.event.client_payload.pull_request.base.ref }}."}'
  ui:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: deploy-cmd
          client-payload: '{"base": "${{ github.event.client_payload.pull_request.base.ref }}", "branch": "${{ github.event.client_payload.pull_request.head.ref }}", "environment": "staging", "event_name": "${{ github.event.client_payload.slash_command.arg1 }}", "pull_request_number": "${{ github.event.client_payload.pull_request.number }}", "release": "false", "task": "staging:ui", "url_prefix": "staging."}'
  web:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: deploy-cmd
          client-payload: '{"base": "${{ github.event.client_payload.pull_request.base.ref }}", "branch": "${{ github.event.client_payload.pull_request.head.ref }}", "environment": "staging", "event_name": "${{ github.event.client_payload.slash_command.arg1 }}", "pull_request_number": "${{ github.event.client_payload.pull_request.number }}", "release": "false", "task": "staging:${{ github.event.client_payload.pull_request.base.ref }}", "url_prefix": "staging.${{ github.event.client_payload.pull_request.base.ref }}."}'
