name: UI
on: pull_request
jobs:
  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - id: change
        run: |
          git fetch --quiet
          if git diff --quiet origin/${{ github.event.pull_request.head.ref }}..origin/${{ github.event.pull_request.base.ref }} -- packages/ui; then
            echo ::set-output name=changed::'false' && exit 0
          else
            echo ::set-output name=changed::'true' && exit 0
          fi
      - if: steps.change.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: "14.1.0"
      - if: steps.change.outputs.changed == 'true'
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - if: steps.change.outputs.changed == 'true'
        id: cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            ${{ steps.yarn-cache-path.outputs.dir }}
          key: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}-
      - if: steps.change.outputs.changed == 'true'
        run: |
          yarn install --frozen-lockfile
          yarn run typescript
      - if: steps.change.outputs.changed == 'true'
        working-directory: packages/ui
        run: |
          yarn run build
          yarn run test
      - if: steps.change.outputs.changed == 'true'
        uses: codecov/codecov-action@v1
        with:
          file: packages/ui/coverage/lcov.info
          name: sentrei
          fail_ci_if_error: true
          flags: ui
      - if: steps.change.outputs.changed == 'true'
        id: secrets
        uses: GoogleCloudPlatform/github-actions/get-secretmanager-secrets@master
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          secrets: |-
            DOCKER_USERNAME:sentrei-master/docker_username
            DOCKER_PASSWORD:sentrei-master/docker_password
            SERVICE_ACCOUNT_EMAIL:sentrei-master/github_master_email
            SERVICE_ACCOUNT_KEY:sentrei-master/github_master_key
      - if: steps.change.outputs.changed == 'true'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "286.0.0"
          service_account_email: ${{ steps.secrets.outputs.SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ steps.secrets.outputs.SERVICE_ACCOUNT_KEY }}
          project_id: "sentrei-${{ github.event.pull_request.base.ref }}"
          export_default_credentials: true
      - if: steps.change.outputs.changed == 'true'
        id: reg
        run: |
          echo "::set-output name=actual::$(git rev-parse HEAD)"
          echo "::set-output name=expected::$(git rev-list -n 1 origin/${{ github.event.pull_request.base.ref }} packages/ui)"
      - if: steps.change.outputs.changed == 'true'
        working-directory: packages/ui
        run: |
          yarn run storycap
          yarn run reg
        env:
          ACTUAL_KEY: ${{ steps.reg.outputs.actual }}
          EXPECTED_KEY: ${{ steps.reg.outputs.expected }}
      - uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: /test
          comment-author: shunkakinoki
      - if: steps.fc.outputs.comment-id != null
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            /test ui
