name: Web
on: pull_request
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14.1.0"
      - id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - id: cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            ${{ steps.yarn-cache-path.outputs.dir }}
          key: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}--
      - id: change
        run: |
          git fetch --quiet
          if git diff --quiet origin/${{ github.event.pull_request.head.ref }}..origin/${{ github.event.pull_request.base.ref }} -- packages/ui packages/web; then
            echo ::set-output name=changed::'false' && exit 0
          else
            echo ::set-output name=changed::'true' && exit 0
          fi
      - if: steps.change.outputs.changed == 'true'
        run: |
          yarn install --frozen-lockfile
          yarn run typescript
          yarn run unsplash
          yarn run build
          yarn install --frozen-lockfile
          yarn run typescript
      - if: steps.change.outputs.changed == 'true'
        working-directory: packages/web
        run: |
          yarn run build
          yarn run cypress:install
          yarn run test
          yarn run analyze
          yarn run relative-ci
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          NODE_ENV: test
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
      - if: steps.change.outputs.changed == 'true'
        uses: codecov/codecov-action@v1
        with:
          file: packages/web/coverage/lcov.info
          name: sentrei
          fail_ci_if_error: true
          flags: web
