name: Web
on: pull_request
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: change
        run: |
          git fetch --quiet
          if git diff --quiet origin/${{ github.event.pull_request.head.ref }}..origin/${{ github.event.pull_request.base.ref }} -- packages/ui packages/web; then
            echo ::set-output name=changed::'false' && exit 0
          else
            echo ::set-output name=changed::'true' && exit 0
          fi
      - if: steps.change.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: "14.1.0"
      - if: steps.change.outputs.changed == 'true'
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - if: steps.change.outputs.changed == 'true'
        id: cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            ${{ steps.yarn-cache-path.outputs.dir }}
          key: |
            yarn-v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}-
      - if: steps.change.outputs.changed == 'true'
        run: |
          yarn install --frozen-lockfile
          yarn run typescript
      - if: steps.change.outputs.changed == 'true'
        working-directory: packages/web
        run: |
          yarn run build
          yarn run export
          yarn run cypress:install
          yarn run test
          yarn run analyze
          yarn run relative-ci
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          NODE_ENV: test
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
      - if: steps.change.outputs.changed == 'true'
        uses: chrnorm/deployment-action@releases/v1
        id: deployment
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
          environment: "Netlify"
          target_url: https://sentrei.netlify.app
      - if: steps.change.outputs.changed == 'true'
        working-directory: packages/web
        run: |
          yarn run netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - if: steps.change.outputs.changed == 'true' && success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          target_url: https://sentrei.netlify.app
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      - if: steps.change.outputs.changed == 'true' && failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          target_url: https://sentrei.netlify.app
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      - if: steps.change.outputs.changed == 'true'
        uses: codecov/codecov-action@v1
        with:
          file: packages/web/coverage/lcov.info
          name: sentrei
          fail_ci_if_error: true
          flags: web
      - uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: /test
          comment-author: shunkakinoki
      - if: steps.fc.outputs.comment-id != null
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            /test web
