name: Web
on: pull_request
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-v1-
      - id: change
        run: |
          git fetch --quiet
          if git diff --quiet origin/${{ github.event.pull_request.head.ref }}..origin/${{ github.event.pull_request.base.ref }} -- packages/ui packages/web; then
            echo ::set-output name=changed::false && exit 0
          else
            echo ::set-output name=changed::true && exit 0
          fi
      - if: steps.change.outputs.changed == 'true' && steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
      - if: steps.change.outputs.changed == 'true'
        run: |
          yarn run tsc
      - if: steps.change.outputs.changed == 'true'
        working-directory: packages/web
        run: |
          yarn run build
      - if: steps.change.outputs.changed == 'true'
        working-directory: packages/web
        run: |
          yarn run build
          yarn run cypress:install
          yarn run test
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          NODE_ENV: test
      - if: steps.change.outputs.changed == 'true'
        uses: codecov/codecov-action@v1
        with:
          file: packages/web/coverage/lcov.info
          name: sentrei
          fail_ci_if_error: true
          flags: web
