name: Yarn
on: pull_request
jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - id: cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
            ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run test
      - if: failure()
        run: |
          yarn run fix
          git config --global user.name 'Shun Kakinoki'
          git config --global user.email 'shunkakinoki@users.noreply.github.com'
          git commit -am "[sentrei-auto-fix]"
          git push
