name: Yarn
on: pull_request
jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Cache node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-v1-
      - name: Install dependencies with yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install
      - name: Run yarn test
        run: |
          yarn run test
      - name: Push modified files
        if: failure()
        run: |
          yarn run fix
          git fetch --quiet
          git config --global user.name 'Shun Kakinoki'
          git config --global user.email 'shunkakinoki@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "[sentrei-auto-fix]"
          git push origin HEAD:${{ github.head_ref }}

