name: Zenhub
on:
  push:
  schedule:
    - cron: "0 15 * * *"
jobs:
  zenhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: dschep/install-pipenv-action@v1
      - id: cache
        uses: actions/cache@master
        with:
          path: .venv
          key: |
            pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            pipenv-
      - run: |
          pipenv install --dev
      - id: day
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/zenhub/day.md
          assignees: shunkakinoki
      - id: morning
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/zenhub/morning.md
          assignees: shunkakinoki
      - id: noon
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/zenhub/noon.md
          assignees: shunkakinoki
      - id: night
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/zenhub/night.md
          assignees: shunkakinoki
      - run: |
          pipenv shell
          python3 .github/zenhub/epic.py -t {{ secrets.ZENHUB_API_TOKEN }} -i ${{ steps.day.outputs.number }}
          python3 .github/zenhub/epic.py -t {{ secrets.ZENHUB_API_TOKEN }} -i ${{ steps.morning.outputs.number }}
          python3 .github/zenhub/epic.py -t {{ secrets.ZENHUB_API_TOKEN }} -i ${{ steps.noon.outputs.number }}
          python3 .github/zenhub/epic.py -t {{ secrets.ZENHUB_API_TOKEN }} -i ${{ steps.night.outputs.number }}
