name: Zenhub
on:
  repository_dispatch:
    types: [zenhub-cmd]
  schedule:
    - cron: "0 16 * * *"
jobs:
  zenhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: dschep/install-pipenv-action@v1
      - id: cache
        uses: actions/cache@master
        with:
          path: .venv
          key: |
            pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            pipenv-
      - run: |
          pipenv install --dev
        env:
          PIPENV_VENV_IN_PROJECT: true
      - id: day
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/zenhub/day.md
          assignees: shunkakinoki
      - id: morning
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/zenhub/morning.md
          assignees: shunkakinoki
      - id: noon
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/zenhub/noon.md
          assignees: shunkakinoki
      - id: night
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/zenhub/night.md
          assignees: shunkakinoki
      - run: |
          pipenv run python .github/scripts/zenhub.py -a day -i ${{ steps.day.outputs.number }}
          pipenv run python .github/scripts/zenhub.py -a session -d ${{ steps.day.outputs.number }} -i ${{ steps.morning.outputs.number }}
          pipenv run python .github/scripts/zenhub.py -a session -d ${{ steps.day.outputs.number }} -i ${{ steps.noon.outputs.number }}
          pipenv run python .github/scripts/zenhub.py -a session -d ${{ steps.day.outputs.number }} -i ${{ steps.night.outputs.number }}
        env:
          ZENHUB_API_TOKEN: ${{ secrets.ZENHUB_API_TOKEN }}
